kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffee-shop
spec:
  selector:
    matchLabels:
      app: coffee-shop
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v1
    spec:
      containers:
      - name: coffee-shop
        image: docker.sebastian-daschner.com/coffee-shop:tmp
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: coffee-shop
  labels:
    app: coffee-shop
spec:
  selector:
    app: coffee-shop
  ports:
  - port: 8080
    name: http
---